context:
  instance: default
  component:
    name: img-responsive--with-overlay
  slides:
    - src: /assets/images/reviews/thumbs/demo-photo-review.png
      link: /assets/images/reviews/demo-photo-review.png
    - src: /assets/images/reviews/thumbs/demo-photo-review.png
      link: /assets/images/reviews/demo-photo-review.png
    - src: /assets/images/reviews/thumbs/demo-photo-review.png
      link: /assets/images/reviews/demo-photo-review.png

variants:
  - name: demo
    context:
      demo: true
