variants:
- name: default
  context:
    icon: /assets/images/icons/benefits/1.png
    label: Более <strong>1 000 наименований</strong> в ассортименте
- name: only-caption_extended
  context:
    mods: [only-caption_extended]
    handle: list-item--only-caption_extended
    caption:
      top: 111
      body: 222
      bottom: 333
- name: product
  context:
    mods: [product]
    handle: list-item--product
    icon: /assets/images/catalog/1.png
    label: Трубы и фитинги 22
    link: product/link-to-product
    priceListLink: product/link-to-download-pricelist
    priceLabel: " прайс"
- name: product--without-pricelist
  context:
    mods: [product]
    handle: list-item--product
    icon: /assets/images/catalog/1.png
    label: Трубы и фитинги 22
    link: /product/link-to-product
    priceListLink: false
- name: news
  context:
    handle: list-item--news
    icon: /assets/images/news/thumbs/demo1.png
    title: Константин Хрюкин арестован за растрату миллиона долларов
    date: 18.04.2016
    anonce: Российский гроссмейстер заявил, что добиться такого результата против действующего чемпиона — уже подвиг. Но останавливаться на достигнутом он не собирается и приложит все усилия, чтобы победить.
    link: /news/demo1.html

- name: certificat
  context:
    mods: [certificat]
    handle: list-item--certificat
    icon: /assets/images/catalog/1.png
    label: Трубы и фитинги 22
    link: /product/link-to-product
    priceListLink: /product/link-to-download-pricelist
