context:
  id: fitingi
  title: Some title
  productPhoto:
    mods: [with-link]
    src: assets/images/catalog/3/product-1/product-photo1.png
    link: assets/images/catalog/3/product-1/product-photo1.png
  productSchemePhoto:
    mods: [with-link]
    src: assets/images/catalog/3/product-1/product-scheme-photo1.png
    link: assets/images/catalog/3/product-1/product-scheme-photo1.png
  textDescription: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto voluptates officiis eveniet quis qui cum, aspernatur velit accusamus, voluptas consequuntur voluptatem sed doloremque perferendis odit eligendi harum deserunt molestiae dolorum temporibus facilis ad a labore! Aliquid ea possimus in impedit voluptate alias eaque nobis, sunt dolorum repudiandae tenetur veniam iure."
  advantages:
  - First advantage
  - Second advantage
  - Third advantage
  - Four advantage
  - Five advantage
  addToCart:
    image: assets/images/icons/addToCart.png
    label: Add to cart
    mods: [with-image, secondary]
