context:
  mods: [news]
  sectionConfig:
    title: Последние новости
  newsList:
    inSlider: true
    listItems:
    - icon: /assets/images/news/thumbs/demo1.png
      title: Константин Хрюкин арестован за растрату миллиона долларов
      date: 18.04.2016
      anonce: Российский гроссмейстер заявил, что добиться такого результата против действующего чемпиона — уже подвиг. Но останавливаться на достигнутом он не собирается и приложит все усилия, чтобы победить.
      link: /news/demo1.html

    - icon: /assets/images/news/thumbs/demo2.png
      title: Двенадцатая партия матча Карлсен-Карякин
      date: 18.04.2016
      anonce: Российский гроссмейстер заявил, что добиться такого результата против действующего чемпиона — уже подвиг. Но останавливаться на достигнутом он не собирается и приложит все усилия, чтобы победить.
      link: /news/demo2.html

    - icon: /assets/images/news/thumbs/demo3.png
      title: Клинцевич предостерег россиян от поездок в Европу на Рождество
      date: 18.04.2016
      anonce: Теперь, согласно регламенту чемпионата, соперникам предстоит встретиться на тай-брейке, который запланирован на 30 ноября.
      link: /news/demo3.html

    - icon: /assets/images/news/thumbs/demo3.png
      title: Клинцевич предостерег россиян от поездок в Европу на Рождество
      date: 18.04.2016
      anonce: Теперь, согласно регламенту чемпионата, соперникам предстоит встретиться на тай-брейке, который запланирован на 30 ноября.
      link: /news/demo3.html

    - icon: /assets/images/news/thumbs/demo3.png
      title: Клинцевич предостерег россиян от поездок в Европу на Рождество
      date: 18.04.2016
      anonce: Теперь, согласно регламенту чемпионата, соперникам предстоит встретиться на тай-брейке, который запланирован на 30 ноября.
      link: /news/demo3.html
