default: slider-version
variants:
- name: slider-version
  context:
    inSlider: true
    listItems:
    - icon: /assets/images/news/thumbs/demo1.png
      title: Константин Хрюкин арестован за растрату миллиона долларов
      date: 18.04.2016
      anonce: Российский гроссмейстер заявил, что добиться такого результата против действующего чемпиона — уже подвиг. Но останавливаться на достигнутом он не собирается и приложит все усилия, чтобы победить.
      link: /news/demo1.html
    - icon: /assets/images/news/thumbs/demo2.png
      title: Константин Хрюкин арестован за растрату миллиона долларов
      date: 18.04.2016
      anonce: Российский гроссмейстер заявил, что добиться такого результата против действующего чемпиона — уже подвиг. Но останавливаться на достигнутом он не собирается и приложит все усилия, чтобы победить.
      link: /news/demo1.html
    - icon: /assets/images/news/thumbs/demo3.png
      title: Константин Хрюкин арестован за растрату миллиона долларов
      date: 18.04.2016
      anonce: Российский гроссмейстер заявил, что добиться такого результата против действующего чемпиона — уже подвиг. Но останавливаться на достигнутом он не собирается и приложит все усилия, чтобы победить.
      link: /news/demo1.html
    - icon: /assets/images/news/thumbs/demo2.png
      title: Константин Хрюкин арестован за растрату миллиона долларов
      date: 18.04.2016
      anonce: Российский гроссмейстер заявил, что добиться такого результата против действующего чемпиона — уже подвиг. Но останавливаться на достигнутом он не собирается и приложит все усилия, чтобы победить.
      link: /news/demo1.html
    - icon: /assets/images/news/thumbs/demo3.png
      title: Константин Хрюкин арестован за растрату миллиона долларов
      date: 18.04.2016
      anonce: Российский гроссмейстер заявил, что добиться такого результата против действующего чемпиона — уже подвиг. Но останавливаться на достигнутом он не собирается и приложит все усилия, чтобы победить.
      link: /news/demo1.html
    - icon: /assets/images/news/thumbs/demo2.png
      title: Константин Хрюкин арестован за растрату миллиона долларов
      date: 18.04.2016
      anonce: Российский гроссмейстер заявил, что добиться такого результата против действующего чемпиона — уже подвиг. Но останавливаться на достигнутом он не собирается и приложит все усилия, чтобы победить.
      link: /news/demo1.html
    - icon: /assets/images/news/thumbs/demo3.png
      title: Константин Хрюкин арестован за растрату миллиона долларов
      date: 18.04.2016
      anonce: Российский гроссмейстер заявил, что добиться такого результата против действующего чемпиона — уже подвиг. Но останавливаться на достигнутом он не собирается и приложит все усилия, чтобы победить.
      link: /news/demo1.html


- name: vertical
  context:
    mods: [vertical]
    bootstrap:
      cols: col-12
    listItems:
    - icon: /assets/images/news/thumbs/demo1.png
      title: Константин Хрюкин арестован за растрату миллиона долларов
      date: 18.04.2016
      anonce: Российский гроссмейстер заявил, что добиться такого результата против действующего чемпиона — уже подвиг. Но останавливаться на достигнутом он не собирается и приложит все усилия, чтобы победить.
      link: /news/demo1.html
    - icon: /assets/images/news/thumbs/demo2.png
      title: Константин Хрюкин арестован за растрату миллиона долларов
      date: 18.04.2016
      anonce: Российский гроссмейстер заявил, что добиться такого результата против действующего чемпиона — уже подвиг. Но останавливаться на достигнутом он не собирается и приложит все усилия, чтобы победить.
      link: /news/demo1.html
    - icon: /assets/images/news/thumbs/demo3.png
      title: Константин Хрюкин арестован за растрату миллиона долларов
      date: 18.04.2016
      anonce: Российский гроссмейстер заявил, что добиться такого результата против действующего чемпиона — уже подвиг. Но останавливаться на достигнутом он не собирается и приложит все усилия, чтобы победить.
      link: /news/demo1.html


- name: bootstrap-version (with cols)
  context:
    bootstrap:
      cols: col-12 col-sm-4
    listItems:
    - icon: /assets/images/news/thumbs/demo1.png
      title: Константин Хрюкин арестован за растрату миллиона долларов
      date: 18.04.2016
      anonce: Российский гроссмейстер заявил, что добиться такого результата против действующего чемпиона — уже подвиг. Но останавливаться на достигнутом он не собирается и приложит все усилия, чтобы победить.
      link: /news/demo1.html
    - icon: /assets/images/news/thumbs/demo2.png
      title: Константин Хрюкин арестован за растрату миллиона долларов
      date: 18.04.2016
      anonce: Российский гроссмейстер заявил, что добиться такого результата против действующего чемпиона — уже подвиг. Но останавливаться на достигнутом он не собирается и приложит все усилия, чтобы победить.
      link: /news/demo1.html
    - icon: /assets/images/news/thumbs/demo3.png
      title: Константин Хрюкин арестован за растрату миллиона долларов
      date: 18.04.2016
      anonce: Российский гроссмейстер заявил, что добиться такого результата против действующего чемпиона — уже подвиг. Но останавливаться на достигнутом он не собирается и приложит все усилия, чтобы победить.
      link: /news/demo1.html
