title: page-title
collated: true
variants:
  - name: default
    context:
      title: Заголовок страницы
  - name: home-title
    context:
      title: Заголовок не жирный (на главной)
      mods: [home]
